## Redirect `cfmm.meshcloud.io` to `cloudfoundation.meshcloud.io`. Both for HTTP & HTTPS
## See https://docs.netlify.com/routing/redirects/rewrites-proxies/#shadowing for the force option
[[redirects]]
  from = "https://cfmm.meshcloud.io/*"
  to = "https://cloudfoundation.meshcloud.io/:splat"
  status = 301
  force = true 

[[redirects]]
  from = "http://cfmm.meshcloud.io/*"
  to = "https://cloudfoundation.meshcloud.io/:splat"
  status = 301
  force = true

## Redirects required for bypassing adblockers with plausible.io
## See https://plausible.io/docs/proxy/guides/netlify
## Contrary to netlify docs, only status=200 works here, see https://github.com/plausible/docs/issues/177
[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 200
  force = true
