## Redirect `cfmm.meshcloud.io` to `cloudfoundation.meshcloud.io`. Both for HTTP & HTTPS
## See https://docs.netlify.com/routing/redirects/rewrites-proxies/#shadowing for the force option
[[redirects]]
  from = "https://cfmm.meshcloud.io/*"
  to = "https://cloudfoundation.meshcloud.io/:splat"
  status = 301
  force = true 

[[redirects]]
  from = "http://cfmm.meshcloud.io/*"
  to = "https://cloudfoundation.meshcloud.io/:splat"
  status = 301
  force = true

## Redirects related to the feedback form.
## Google App Script cannot be called directly from Vue due to CORS policy.
[[redirects]]
  from = "/api/feedback"
  to = "https://script.google.com/macros/s/AKfycbyXJmPTWuiaCr13-VUyZnV8bSsFemc5Ahm8n3n593GL_UrZTSZ9Ux0x439RY-mZ8vlV/exec"
  status = 200
  force = true

## Redirects required for bypassing adblockers with plausible.io
## See https://plausible.io/docs/proxy/guides/netlify
## Contrary to netlify docs, only status=200 works here, see https://github.com/plausible/docs/issues/177
[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 200
  force = true


## Redirects for individual pages that we moved/renamed but we want to make sure
## we don't confuse google

[[redirects]]
  from = "/maturity-model/what-is-the-cloud-foundation-maturity-model.html"
  to = "/understanding-cloud-foundation/"
  status = 301

[[redirects]]
  from = "/maturity-model/building-block-reference.html"
  to = "/maturity-model/what-is-a-building-block.html"
  status = 301
  
[[redirects]]
  from = "/maturity-model/security-and-compliance/central-management-of-tenant-tags-and-metadata.html"
  to = "/maturity-model/security-and-compliance/multi-cloud-tagging-policy.html"
  status = 301