services:
  - type: web
    name: cloudfoundation-website
    env: static
    # we have to unshallow the git repo during builds to enable proper sitemap generation. Unforunately that means
    # wen eed to run this extra command before the actual build
    # see https://github.com/meshcloud/cloudfoundation/issues/150
    buildCommand: git remote add origin https://oauth2:$(cat .github_pat)@github.com/meshcloud/cloudfoundation.git && git fetch --unshallow && yarn docs:build 
    staticPublishPath: ./docs/.vuepress/dist
    pullRequestPreviewsEnabled: true
    domains:
      - cloudfoundation.org
    routes:
      ## Redirects related to the feedback form.
      ## Google App Script cannot be called directly from Vue due to CORS policy.
      - type: rewrite
        source: /api/feedback
        destination: https://script.google.com/macros/s/AKfycbyXJmPTWuiaCr13-VUyZnV8bSsFemc5Ahm8n3n593GL_UrZTSZ9Ux0x439RY-mZ8vlV/exec
      ## Redirects required for bypassing adblockers with plausible.io
      ## See https://plausible.io/docs/proxy/guides/netlify
      ## Contrary to netlify docs, only status=200 works here, see https://github.com/plausible/docs/issues/177
      - type: rewrite
        source: /api/event
        destination: https://plausible.io/api/event
      ## Redirects for individual pages that we moved/renamed but we want to make sure
      ## we don't confuse google
      - type: redirect
        source: /maturity-model/what-is-the-cloud-foundation-maturity-model.html
        destination: /understanding-cloud-foundation/
      - type: redirect
        source: /maturity-model/what-is-a-building-block.html
        destination: /understanding-cloud-foundation/what-is-a-building-block.html
      - type: redirect
        source: /maturity-model/security-and-compliance/central-management-of-tenant-tags-and-metadata.html
        destination: /maturity-model/security-and-compliance/multi-cloud-tagging-policy.html
      - type: redirect
        source: /maturity-model/maturity-model/tenant-management/multi-cloud-tenant-database.html
        destination: /maturity-model/tenant-management/self-service-multi-cloud-tenant-database.html
      - type: redirect
        source: /maturity-model/security-and-compliance/resource-policies-blacklisting.html
        destination: /maturity-model/security-and-compliance/service-and-location-restrictions.html
      - type: redirect
        source: /maturity-model/security-and-compliance/automated-security-scanning.html
        destination: /maturity-model/security-and-compliance/resource-configuration-scanning.html
      # fix some Google SEO "duplicate without user-selected canonical" issues, due to trailing slash
      - type: redirect
        source: /understanding-cloud-foundation
        destination: /understanding-cloud-foundation/