name: "Update Stats"
on:
  workflow_dispatch:
    inputs: 
      description:
        description: 'description'
        required: false
        default: 'manually triggered stats update'
  push: # trigger when someone pushes to main (e.g. by merging a PR)
    branches:
      - "main"
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Update Stats
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: prepare credentials.json
        run: |
          echo "${{ secrets.MESHBARN_FIELD_CFMM_WRITER_CREDENTIALS_JSON}}" | base64 --decode > credentials.json
          ls -lah credentials.json
      - run: yarn install --frozen-lockfile
      - run: yarn stats
